- include: install.yml
  tags: [postgresql, postgresql-install]

- include: extensions.yml
  tags: [postgresql, postgresql-extensions]

- include: configure.yml
  tags: [postgresql, postgresql-configure]

- include: databases.yml
  tags: [postgresql, postgresql-databases]

- include: users.yml
  tags: [postgresql, postgresql-users]

- include: vagrant_user.yml
  tags: [postgresql, postgresql-vagrant-user]


